name = "Graphon"
uuid = "e0c12bfd-47d7-434e-afb7-632611640ca5"
authors = ["Jake Grainger", "Charles Dufour"]
version = "0.0.1"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
